/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Calculo;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author Mailyn Vargas
 */
public class Calculos extends javax.swing.JFrame {

    /**
     * Creates new form Calculos
     */
    public Calculos() {
        initComponents();
        
    }

    public JLabel getLbl_RResta() {
        return Lbl_RResta;
    }

    public void setLbl_RResta(JLabel Lbl_RResta) {
        this.Lbl_RResta = Lbl_RResta;
    }

    public JLabel getLbl_RSuma() {
        return Lbl_RSDivicion;
    }

    public void setLbl_RSuma(JLabel Lbl_RSuma) {
        this.Lbl_RSDivicion = Lbl_RSuma;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Lbl_Numero_uno = new javax.swing.JLabel();
        Lbl_Numero_Dos = new javax.swing.JLabel();
        Txt_Numero_Uno = new javax.swing.JTextField();
        Txt_Numero_Dos = new javax.swing.JTextField();
        Btn_Generar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Lbl_RSDivicion = new javax.swing.JLabel();
        Lbl_RResta = new javax.swing.JLabel();
        Lbl_resultado_Suma = new javax.swing.JLabel();
        Lbl_Resultado_Resta = new javax.swing.JLabel();
        Lbl_RSuma1 = new javax.swing.JLabel();
        Lbl_RSMultiplicacion = new javax.swing.JLabel();
        Lbl_Resultado_Multiplicacion = new javax.swing.JLabel();
        Lbl_Resultado_Divicon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 153));
        jLabel1.setText("Practica Ejercicios Matematicos ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Debes Ingresar dos numeros para ejecutar acciones y presionar el boton ejecutar");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        Lbl_Numero_uno.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Lbl_Numero_uno.setForeground(new java.awt.Color(153, 0, 0));
        Lbl_Numero_uno.setText("Numero uno:");
        jPanel1.add(Lbl_Numero_uno, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, -1, -1));

        Lbl_Numero_Dos.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Lbl_Numero_Dos.setForeground(new java.awt.Color(153, 0, 0));
        Lbl_Numero_Dos.setText("Numero Dos:");
        jPanel1.add(Lbl_Numero_Dos, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, 20));

        Txt_Numero_Uno.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Txt_Numero_Uno.setForeground(new java.awt.Color(0, 0, 153));
        jPanel1.add(Txt_Numero_Uno, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 30, -1));

        Txt_Numero_Dos.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Txt_Numero_Dos.setForeground(new java.awt.Color(0, 0, 153));
        jPanel1.add(Txt_Numero_Dos, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 30, -1));

        Btn_Generar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Btn_Generar.setForeground(new java.awt.Color(0, 153, 153));
        Btn_Generar.setText("Generar");
        Btn_Generar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_GenerarActionPerformed(evt);
            }
        });
        jPanel1.add(Btn_Generar, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 100, 90, 30));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 255), null));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Lbl_RSDivicion.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Lbl_RSDivicion.setForeground(new java.awt.Color(153, 0, 102));
        Lbl_RSDivicion.setText("El Resultado de la divicion es:");
        jPanel2.add(Lbl_RSDivicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

        Lbl_RResta.setBackground(new java.awt.Color(255, 255, 255));
        Lbl_RResta.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Lbl_RResta.setForeground(new java.awt.Color(153, 0, 102));
        Lbl_RResta.setText("El Resultado de la resta es:");
        jPanel2.add(Lbl_RResta, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, -1));

        Lbl_resultado_Suma.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Lbl_resultado_Suma.setForeground(new java.awt.Color(153, 153, 153));
        Lbl_resultado_Suma.setText("Respuesta");
        jPanel2.add(Lbl_resultado_Suma, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 80, 20));

        Lbl_Resultado_Resta.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Lbl_Resultado_Resta.setForeground(new java.awt.Color(153, 153, 153));
        Lbl_Resultado_Resta.setText("Respuesta");
        jPanel2.add(Lbl_Resultado_Resta, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, -1, -1));

        Lbl_RSuma1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Lbl_RSuma1.setForeground(new java.awt.Color(153, 0, 102));
        Lbl_RSuma1.setText("El Resultado de la suma es:");
        jPanel2.add(Lbl_RSuma1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        Lbl_RSMultiplicacion.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Lbl_RSMultiplicacion.setForeground(new java.awt.Color(153, 0, 102));
        Lbl_RSMultiplicacion.setText("El Resultado de la Multiplicacion es:");
        jPanel2.add(Lbl_RSMultiplicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));

        Lbl_Resultado_Multiplicacion.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Lbl_Resultado_Multiplicacion.setForeground(new java.awt.Color(153, 153, 153));
        Lbl_Resultado_Multiplicacion.setText("Respuesta");
        jPanel2.add(Lbl_Resultado_Multiplicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, -1, 20));

        Lbl_Resultado_Divicon.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Lbl_Resultado_Divicon.setForeground(new java.awt.Color(153, 153, 153));
        Lbl_Resultado_Divicon.setText("Respuesta");
        jPanel2.add(Lbl_Resultado_Divicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 470, 170));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 540, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_GenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_GenerarActionPerformed
      Calculo cls = new Calculo();
      Integer numeroUno = Integer.parseInt(Txt_Numero_Uno.getText());
      Integer numeroDos = Integer.parseInt(Txt_Numero_Dos.getText()); 
      // enviar al metodo
     cls.CalculoMatematico(numeroUno,numeroDos,this);
        
    }//GEN-LAST:event_Btn_GenerarActionPerformed

    public JLabel getLbl_Resultado_Resta() {
        return Lbl_Resultado_Resta;
    }

    public void setLbl_Resultado_Resta(JLabel Lbl_Resultado_Resta) {
        this.Lbl_Resultado_Resta = Lbl_Resultado_Resta;
    }

    public JLabel getLbl_resultado_Suma() {
        return Lbl_resultado_Suma;
    }

    public void setLbl_resultado_Suma(JLabel Lbl_resultado_Suma) {
        this.Lbl_resultado_Suma = Lbl_resultado_Suma;
    }  
    public JLabel getLbl_Resultado_Multiplicacion() {
        return Lbl_Resultado_Multiplicacion;
    }

    public void setLbl_Resultado_Multiplicacion(JLabel Lbl_Resultado_Multiplicacion) {
        this.Lbl_Resultado_Multiplicacion = Lbl_Resultado_Multiplicacion;
    }

    public JLabel getLbl_resultado_Divicion() {
        return Lbl_Resultado_Divicon;
    }

    public void setLbl_resultado_Divicion(JLabel Lbl_resultado_Multiplicacion) {
        this.Lbl_Resultado_Divicon = Lbl_resultado_Multiplicacion;
    }

    /**
     * @param args the command line arguments
     */
  
    public JButton getBtn_Generar() {
        return Btn_Generar;
    }

    public void setBtn_Generar(JButton Btn_Generar) {
        this.Btn_Generar = Btn_Generar;
    }

    public JLabel getLbl_Numero_Dos() {
        return Lbl_Numero_Dos;
    }

    public void setLbl_Numero_Dos(JLabel Lbl_Numero_Dos) {
        this.Lbl_Numero_Dos = Lbl_Numero_Dos;
    }

    public JLabel getLbl_Numero_uno() {
        return Lbl_Numero_uno;
    }

    public void setLbl_Numero_uno(JLabel Lbl_Numero_uno) {
        this.Lbl_Numero_uno = Lbl_Numero_uno;
    }

    public JTextField getTxt_Numero_Dos() {
        return Txt_Numero_Dos;
    }

    public void setTxt_Numero_Dos(JTextField Txt_Numero_Dos) {
        this.Txt_Numero_Dos = Txt_Numero_Dos;
    }

    public JTextField getTxt_Numero_Uno() {
        return Txt_Numero_Uno;
    }

    public void setTxt_Numero_Uno(JTextField Txt_Numero_Uno) {
        this.Txt_Numero_Uno = Txt_Numero_Uno;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel7() {
        return Lbl_resultado_Suma;
    }

    public void setjLabel7(JLabel jLabel7) {
        this.Lbl_resultado_Suma = jLabel7;
    }

    public JLabel getjLabel8() {
        return Lbl_Resultado_Resta;
    }

    public void setjLabel8(JLabel jLabel8) {
        this.Lbl_Resultado_Resta = jLabel8;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JPanel getjPanel2() {
        return jPanel2;
    }

    public void setjPanel2(JPanel jPanel2) {
        this.jPanel2 = jPanel2;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Generar;
    private javax.swing.JLabel Lbl_Numero_Dos;
    private javax.swing.JLabel Lbl_Numero_uno;
    private javax.swing.JLabel Lbl_RResta;
    private javax.swing.JLabel Lbl_RSDivicion;
    private javax.swing.JLabel Lbl_RSMultiplicacion;
    private javax.swing.JLabel Lbl_RSuma1;
    private javax.swing.JLabel Lbl_Resultado_Divicon;
    private javax.swing.JLabel Lbl_Resultado_Multiplicacion;
    private javax.swing.JLabel Lbl_Resultado_Resta;
    private javax.swing.JLabel Lbl_resultado_Suma;
    private javax.swing.JTextField Txt_Numero_Dos;
    private javax.swing.JTextField Txt_Numero_Uno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
